# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Requirements
      run: |
        brew install docker
        brew install docker-compose
    - name: Get swift version
      run: swift --version
    - name: Start colima
      run: colima start
    - name: Start docker container
      run: docker-compose up -d
    - name: List available devices
      run: xcrun simctl list devicetypes 
    - name: Build and run tests
      run: xcodebuild test -scheme mountebankSwift  -destination 'platform=iOS Simulator,name=iPhone 14 Pro'

