# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Print active directory
      run: "pwd"
    - name: List directory files
      run: "ls -a ./"
    - name: Start Docker Compose
      uses: isbang/compose-action@v1.5.1
      with:
        compose-file: "./docker-compose.yml"
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1.25.0
    - name: Build
      run: swift build -v
